apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
  labels:
    app: register-app 
spec:
  selector:
    app: devops-project

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
